2version: "3"
volumes:
  data:
  export:
services:
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
