spring:
    application:
        name: cube-ms-user

    datasource:
        url: ${POSTGRESQL_URL}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}

    jpa:
        show-sql: true
        database: POSTGRESQL
        hibernate:
            format_sql: true
            ddl-auto: update
            generate-ddl: true

    cloud:
        openfeign:
            client:
                config:
                    asaas:
                        url: ${ASAAS_URL}
    config:
        import: optional:configserver:http://localhost:8888

    flyway:
        locations: 'classpath:db/migration'

security:
    token:
        secret: "${JWT_SECRET}"
        minutesToExpire: "${TOKEN_MINUTES_TO_EXPIRE:120}"

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:https://cube-ms-eureka.onrender.com:8761/eureka/}
    instance:
      hostname: ${EUREKA_INSTANCE:65b654dc50e7.ngrok-free.app}
      secure-port: 443
      secure-port-enabled: true
      non-secure-port-enabled: false
      prefer-ip-address: false
server:
    port: 8080
    error:
        include-message: always

asaas:
    api-key: "${ASAAS_API_KEY}"
