spring:
    application:
        name: cube-ms-user

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres

    jpa:
        show-sql: true
        database: POSTGRESQL
        hibernate:
            format_sql: true
            ddl-auto: update
            generate-ddl: true

    flyway:
        locations: 'classpath:db/migration'

security:
    token:
        secret: "${JWT_SECRET:JWT_SECRET}"
        minutesToExpire: "${TOKEN_MINUTES_TO_EXPIRE:120}"

server:
    error:
        include-message: always