spring:
    application:
        name: cube-ms-user

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres

    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    flyway:
        locations: 'classpath:db/migration'

server:
    error:
        include-message: always